Repository dhvanilshah-tenable/pyTenable, pull requests merged in 2022-03, with the labels that each got.

#49 vm/agent_exclusion
  docs/api/io/v3/vm/agent_exclusions.rst
  tenable/io/v3/vm/__init__.py
  tenable/io/v3/vm/agent_exclusions/__init__.py
  tenable/io/v3/vm/agent_exclusions/api.py
  tenable/io/v3/vm/agent_exclusions/schema.py
  tenable/io/v3/vm/scans/__init__.py
  tenable/io/v3/vm/scans/api.py
  tests/io/v3/vm/agent_exclusions/__init__.py
  tests/io/v3/vm/agent_exclusions/test_agent_exclusions.py
  tests/io/v3/vm/agent_exclusions/test_agent_exclusions_schema.py
Labels: vm

#59 vm/Exclusions
  tenable/io/v3/vm/__init__.py
  tenable/io/v3/vm/exclusions/__init__.py
  tenable/io/v3/vm/exclusions/api.py
  tenable/io/v3/vm/exclusions/schema.py
  tests/io/v3/vm/exclusions/__init__.py
  tests/io/v3/vm/exclusions/import_exclusion_test_file.csv
  tests/io/v3/vm/exclusions/test_exclusions_api.py
  tests/io/v3/vm/exclusions/test_exclusions_schema.py
Labels: vm

#86 vm/agent_groups
  tenable/io/base/schemas/filters/base.py
  tenable/io/v3/base/schema/explore/filters.py
  tenable/io/v3/vm/agent_groups/api.py
  tenable/io/v3/vm/agent_groups/schema.py
  tests/io/v3/vm/agent_groups/objects.py
  tests/io/v3/vm/agent_groups/test_agent_groups_api.py
  tests/io/v3/vm/agent_groups/test_agent_groups_schema.py
Labels: vm, search

#85 vm/agent-config
  tenable/io/v3/vm/__init__.py
  tenable/io/v3/vm/agent_config/api.py
  tenable/io/v3/vm/agent_config/schema.py
  tests/io/v3/vm/agent_config/objects.py
  tests/io/v3/vm/agent_config/test_agent_config_api.py
  tests/io/v3/vm/agent_config/test_agent_config_schema.py
Labels: vm

#83 v3/iterators_tests
  tests/io/v3/base/test_csv_iterator.py
  tests/io/v3/base/test_explore.py
  tests/io/v3/base/test_search_iterator.py
Labels: io

#48 mssp/logos
  docs/api/io/v3/mssp/logos.rst
  tenable/io/v3/mssp/__init__.py
  tenable/io/v3/mssp/logos/__init__.py
  tenable/io/v3/mssp/logos/api.py
  tenable/io/v3/mssp/logos/schema.py
  tests/io/v3/mssp/logos/__init__.py
  tests/io/v3/mssp/logos/test_api.py
  tests/io/v3/mssp/logos/test_image.png
  tests/io/v3/mssp/logos/test_schema.py
Labels: mssp

#61 vm/audit_log
  docs/api/io/v3/vm/audit_log.rst
  tenable/io/v3/vm/__init__.py
  tenable/io/v3/vm/audit_log/__init__.py
  tenable/io/v3/vm/audit_log/api.py
  tests/io/v3/vm/audit_log/__init__.py
  tests/io/v3/vm/audit_log/test_audit_log_api.py
Labels: vm

#65 vm/scanners
  tenable/io/v3/vm/scanners/api.py
  tenable/io/v3/vm/scanners/schema.py
  tests/io/v3/vm/scanners/test_scanners_api.py
  tests/io/v3/vm/scanners/test_scanners_schema.py
Labels: vm

#64 platform/connectors
  docs/api/io/v3/connectors.rst
  tenable/io/v3/__init__.py
  tenable/io/v3/connectors/__init__.py
  tenable/io/v3/connectors/api.py
  tenable/io/v3/connectors/schema.py
  tests/io/v3/connectors/__init__.py
  tests/io/v3/connectors/test_connectors_api.py
  tests/io/v3/connectors/test_connectors_schema.py
Labels: platform

#67 vm/plugins
  tenable/io/v3/vm/plugins/api.py
  tenable/io/v3/vm/plugins/iterator.py
  tests/io/v3/vm/plugins/objects.py
  tests/io/v3/vm/plugins/test_plugins_api.py
Labels: vm

#55 Remediation scans v3
  docs/api/io/v3/vm/remediation_scans.rst
  tenable/io/v3/vm/__init__.py
  tenable/io/v3/vm/remediation_scans/__init__.py
  tenable/io/v3/vm/remediation_scans/api.py
  tenable/io/v3/vm/remediation_scans/schema.py
  tests/io/v3/vm/remediation_scans/__init__.py
  tests/io/v3/vm/remediation_scans/test_remediation_scans_api.py
  tests/io/v3/vm/remediation_scans/test_remediation_scans_schema.py
Labels: vm

#52 vm/scans
  docs/api/io/v3/vm/scans.rst
  tenable/constants.py
  tenable/io/v3/vm/scans/api.py
  tenable/io/v3/vm/scans/iterator.py
  tenable/io/v3/vm/scans/schema.py
  tests/io/v3/vm/scans/__init__.py
  tests/io/v3/vm/scans/scans_export.txt
  tests/io/v3/vm/scans/scans_targets.txt
  tests/io/v3/vm/scans/test_scans_api.py
  tests/io/v3/vm/scans/test_scans_schema.py
  tests/io/v3/vm/scans/text_file.txt
Labels: vm

#78 Users/search_support
  tenable/io/v3/users/api.py
  tenable/io/v3/users/schema.py
  tests/io/v3/users/test_users_api.py
  tests/io/v3/users/test_users_schema.py
Labels: search

#82 VM/ Folders: Adding search
  tenable/io/v3/vm/folders/api.py
  tests/io/v3/vm/folders/test_folders_api.py
Labels: vm, search

#79 vm/credentials (search method)
  tenable/io/v3/vm/credentials/api.py
  tests/io/v3/vm/credentials/test_credentials_api.py
Labels: vm, search

#75 Scanner-Groups: Added search endpoint support
  tenable/io/v3/vm/scanner_groups/api.py
  tests/io/v3/vm/scanner_groups/test_scanner_group_api.py
Labels: vm

#72 vm/networks (search method)
  tenable/io/v3/vm/networks/api.py
  tenable/io/v3/vm/networks/iterator.py
  tests/io/v3/vm/networks/test_networks_api.py
Labels: vm

#51 vm/editor
  docs/api/io/v3/vm/editor.rst
  tenable/io/v3/vm/__init__.py
  tenable/io/v3/vm/editor/__init__.py
  tenable/io/v3/vm/editor/api.py
  tenable/io/v3/vm/editor/schema.py
  tests/io/v3/vm/editor/__init__.py
  tests/io/v3/vm/editor/audit.txt
  tests/io/v3/vm/editor/objects.py
  tests/io/v3/vm/editor/test_editor_api.py
  tests/io/v3/vm/editor/test_editor_schema.py
Labels: vm

#63 [vm & was] Vulnerabilities
  docs/api/io/v3/vm/vulnerabilities.rst
  docs/api/io/v3/was/vulnerabilities.rst
  tenable/io/__init__.py
  tenable/io/v3/vm/__init__.py
  tenable/io/v3/vm/vulnerabilities/__init__.py
  tenable/io/v3/vm/vulnerabilities/api.py
  tenable/io/v3/vm/vulnerabilities/schema.py
  tenable/io/v3/was/__init__.py
  tenable/io/v3/was/vulnerabilities/__init__.py
  tenable/io/v3/was/vulnerabilities/api.py
  tests/io/v3/vm/vulnerabilities/__init__.py
  tests/io/v3/vm/vulnerabilities/objects.py
  tests/io/v3/vm/vulnerabilities/test_vm_vulnerability_api.py
  tests/io/v3/vm/vulnerabilities/test_vm_vulnerability_schema.py
  tests/io/v3/was/vulnerabilities/__init__.py
  tests/io/v3/was/vulnerabilities/test_was_vulnerabilities_api.py
Labels: vm, was

#39 vm/policies
  docs/api/io/v3/vm/policies.rst
  tenable/io/v3/__init__.py
  tenable/io/v3/vm/__init__.py
  tenable/io/v3/vm/policies/__init__.py
  tenable/io/v3/vm/policies/api.py
  tenable/io/v3/vm/policies/schema.py
  tests/io/v3/vm/policies/__init__.py
  tests/io/v3/vm/policies/policies_test.nessus
  tests/io/v3/vm/policies/test_policies_api.py
  tests/io/v3/vm/policies/test_policies_schema.py
Labels: io
